// <auto-generated />
using System;
using BuildCalculator.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildCalculator.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20230128133727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("BuildCalculator.Data.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("dmg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("energia")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("itemClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("klute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("konda")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mana")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("moc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("obuch")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ogien")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("sieczne")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("sila")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("urok")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("wiedza")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("zimno")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("zreka")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemId");

                    b.HasIndex("itemClassId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("BuildCalculator.Data.ItemClass", b =>
                {
                    b.Property<int>("itemClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("itemClassId");

                    b.ToTable("itemClasses");

                    b.HasData(
                        new
                        {
                            itemClassId = 1,
                            name = "zbroja"
                        },
                        new
                        {
                            itemClassId = 2,
                            name = "helm"
                        },
                        new
                        {
                            itemClassId = 3,
                            name = "naszyjnik"
                        },
                        new
                        {
                            itemClassId = 4,
                            name = "rekawice"
                        },
                        new
                        {
                            itemClassId = 5,
                            name = "bron"
                        },
                        new
                        {
                            itemClassId = 6,
                            name = "tarcza"
                        },
                        new
                        {
                            itemClassId = 7,
                            name = "pas"
                        },
                        new
                        {
                            itemClassId = 8,
                            name = "buty"
                        },
                        new
                        {
                            itemClassId = 9,
                            name = "pierscien"
                        },
                        new
                        {
                            itemClassId = 10,
                            name = "spodnie"
                        },
                        new
                        {
                            itemClassId = 11,
                            name = "peleryna"
                        });
                });

            modelBuilder.Entity("BuildCalculator.Data.Item", b =>
                {
                    b.HasOne("BuildCalculator.Data.ItemClass", "itemClass")
                        .WithMany("items")
                        .HasForeignKey("itemClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("itemClass");
                });

            modelBuilder.Entity("BuildCalculator.Data.ItemClass", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
